# SPDX-FileCopyrightText: None
# SPDX-License-Identifier: CC0-1.0

include:
  - project: sysadmin/ci-utilities
    file:
      - /gitlab-templates/linux-qt6.yml
      - /gitlab-templates/freebsd-qt6.yml

# SPDX-License-Identifier: BSD-2-Clause
# SPDX-FileCopyrightText: 2024 Harald Sitter <sitter@kde.org>

reuse:
  image:
    name: fsfe/reuse:latest
    entrypoint: [""]
  stage: build
  tags:
    - Linux
  interruptible: true
  script:
    - cat .kde-reuse-ignore >> .gitignore
    - git ls-files --exclude-standard --ignored -c --directory | xargs rm
    - reuse lint
