#!/usr/bin/env python3

# A tool to fetch all debuginfo files in a core file.

# SPDX-License-Identifier: BSD-2-Clause
# SPDX-FileCopyrightText: 2026 Harald Sitter <sitter@kde.org>

import subprocess
import sys

out = subprocess.check_output(["eu-unstrip", "--list-only", *sys.argv[1:]])
if sys.argv[1] == "--help" or sys.argv[1] == "-h":
    print(out.decode("utf-8"))
    sys.exit(0)

procs = []
for line in out.splitlines():
    print(line)
    if not line.strip():
        continue

    start_and_length, build_id_and_address, elf_file, dwarf_file, mapping_name = line.split(b' ', 4)
    if build_id_and_address == b'-':
        continue

    build_id, _vaddress = build_id_and_address.split(b'@', 1)
    if build_id == b'':
        continue

    procs.append(subprocess.Popen(["debuginfod-find", "debuginfo", build_id], stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL))

for proc in procs:
    proc.wait()
    if proc.returncode != 0:
        print("F", end="")
    else:
        print(".", end="")
