# KDE Config File
[Desktop Entry]
Type=Application
Exec=${KDE_INSTALL_FULL_LIBEXECDIR}/drkonqi
Name=Dr Konqi
Name[ar]=د.كوينكي
Name[ast]=Dr Konqi
Name[az]=Dr Konqi
Name[bg]=Dr Konqi
Name[ca]=Dr Konqi
Name[ca@valencia]=Dr Konqi
Name[cs]=Dr Konqi
Name[da]=Dr Konqi
Name[de]=Dr Konqi
Name[el]=Dr Konqi
Name[en_GB]=Dr Konqi
Name[eo]=Dr Konqi
Name[es]=Dr Konqi
Name[et]=Dr Konqi
Name[eu]=Dr Konqi
Name[fi]=Dr Konqi
Name[fr]=Dr Konqi
Name[gl]=Dr Konqi
Name[he]=Dr Konqi
Name[hu]=Dr Konqi
Name[ia]=Dr Konqi
Name[id]=Dr Konqi
Name[is]=Dr Konqi
Name[it]=Dr Konqi
Name[ja]=Dr Konqi
Name[ka]=Dr Konqi
Name[ko]=Dr Konqi
Name[lt]=Dr. Konqi
Name[lv]=Dr Konqi
Name[nb]=Dr Konqi
Name[nl]=Dr Konqi
Name[nn]=Dr Konqi
Name[pa]=ਡਾ Konqi
Name[pl]=Dr Konqi
Name[pt]=Dr Konqi
Name[pt_BR]=Dr Konqi
Name[ro]=Dr. Konqi
Name[ru]=Dr Konqi
Name[sk]=Dr Konqi
Name[sl]=Dr Konqi
Name[sr]=Др Конки
Name[sr@ijekavian]=Др Конки
Name[sr@ijekavianlatin]=DrKonqi
Name[sr@latin]=DrKonqi
Name[sv]=Dr Konqi
Name[tg]=Dr Konqi
Name[tr]=Dr. Konqi
Name[uk]=Dr Konqi
Name[vi]=Dr Konqi
Name[x-test]=xxDr Konqixx
Name[zh_CN]=Dr Konqi
Name[zh_TW]=Dr Konqi
Icon=tools-report-bug
NoDisplay=true
